### ISSUE TITLE
Scott Wlaschin's AsyncResult missing functionality

### ISSUE THREAD

**Issue by deyanp** [demystifyfp/FsToolkit.ErrorHandling#60]
Do you intend to implement some of the functions Scott Wlaschin has in its AsyncResult/Result modules, e.g.

AsyncResult.catch
AsyncResult.ofAsync
AsyncResult.ofSuccess
AsyncResult.ofError
AsyncResult.ofResult?

https://github.com/swlaschin/DomainModelingMadeFunctional/blob/master/src/OrderTakingEvolved/Result.fs

**Comment by TheAngryByrd** [comment]
If you're using the Computation Expression for `asyncResult` most of these are built in.  If you're trying to compose solely with functions, these are missing. This would make for a great first PR 😃 .

**Comment by TheAngryByrd** [comment]
We would also want similar functions added to `TaskResult` and `JobResult`.

**Comment by svdHero** [comment]
@TheAngryByrd, following our recent Slack discussion about error handling, I'd love to work on this and give something back to the community. However, this would be my first F# PR ever and it might take a while, before I am addressing this in my project.

Any advice how to contribute? Which toolchain / tools should I use? I am using Visual Studio 2019 with Nuget and don't know anything about Package, FAKE, yet.

Also, I didn't know Expecto even existed until 5 minutes ago. :laughing:

**Comment by TheAngryByrd** [comment]
Good point, we don't have prerequisites on the README.  I'll have to add those.  Since we build for `netstandard2.0;net461` you'll want at least dotnet core 2.1 and at least full framework 4.6.1 installed.  Additionally since we transpile to javascript with Fable, you'll want to have [node LTS](https://nodejs.org/en/) installed. 

Also it looks like we need to make a `build.cmd` for this project too. 

As for right now you can do 

 ```
dotnet tool install fake-cli -g
fake run build.fsx target RunFableTests
```

Report back any errors so we can fix up this experience when contributing from windows.

**Comment by rahicks26** [comment]
Is anyone actively working on this? If not might be a fun weekend project for me

**Comment by svdHero** [comment]
No, not right now. Unfortunately, I've never managed to give it a try due to other projects. Please, go ahead.

**Comment by rahicks26** [comment]
Sounds good. I got tied up last weekend but I should be able to get started soon.  As I understand it what we want to do here is add some static helpers like:

**Comment by TheAngryByrd** [comment]
Closign via #124
