### ISSUE TITLE
Source overload breaks `match!`

### ISSUE THREAD

**Issue by TheAngryByrd** [demystifyfp/FsToolkit.ErrorHandling#85]
In https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/83 I started using the `Source` member to help with maintainability.  However after using it in a work project, `match!` expressions became broken.  @baronfel identified the issue in the F# compiler and have a PR  open https://github.com/dotnet/fsharp/pull/9407.  

This is just a tracking issue for the upstream problem so others can find this easily.

**Comment by TheAngryByrd** [comment]
I'm going to keep this open until F# release a new preview with the fix

**Comment by TheAngryByrd** [comment]
Pretty sure this is fixed in F# 5.0

**Comment by JohnTheGr8** [comment]
I had the library pinned to v1.3.1 for a while because of this issue. Upgrading now to v1.3.2 (or latest) still gives me issues unfortunately...

Here's a quick example:

```fsharp
#r "nuget: FsToolkit.ErrorHandling, 1.3.1"
open FsToolkit.ErrorHandling

let tryDoSomething () = 
    asyncResult {
        match! AsyncResult.retn () with
        | Result.Ok   () -> printfn "ok"
        | Result.Error _ -> printfn "not ok"
    }
```

This works fine, but if I change `1.3.1` to `1.3.2` I get:

```
          | Result.Ok   () -> printfn "ok"
  ----------^^^^^^^^^^^^^^

stdin(7,11): error FS0001: This expression was expected to have type
    'unit'    
but here has type
    'Result<'a,'b>'
```

Any thoughts? Could this still be a compiler issue?

**Comment by baronfel** [comment]
This isn't the same issue as what was originally linked.  `AsyncResult.retn ()` returns an `Async<Result<unit, obj>>`, and the `match` inside an `asyncResult` CE desugars to `asyncResult.Bind(ar: Async<Result<'t, 'e>>, binder: 't -> Async<Result<'s, 'e>>): Async<Result<'s, 'e>)`, meaning you can't 'just' run the Async portion inside the `asyncResult` CE, you have to run the Async and handle the inner Result portion.  If you do want to do error handling like this you have two options:

* run the asyncResult value in an `async` CE instead, so that only the outer async layer is binded to, or
* map the `AsyncResult.retn()` to an `Async<unit>` and inside the mapping function do the printing/error handling you want

**Comment by JohnTheGr8** [comment]
Thanks for the quick response and explanation. Does this mean this is an expected "limitation" (or "constraint", whatever you want to call it, I realize this is an uncommon use case) from switching to `Source` overloads in 1.3.2?

In any case, I only wanted to flag this up in case it was a corner case that had been overlooked... I have already refactored my code (using `foldResult` actually) to allow me to upgrade the package to latest version.

Thank you!

**Comment by baronfel** [comment]
@JohnTheGr8 I'd say that's the correct way to think of it, yeah. Adding many `Bind` overloads like this library did previously may have made it feel more 'open', but it was a maintenance nightmare and also very hard to reason about what actually was happening in every possible case. With `Source`, the mental and technical overhead is greatly reduced, which should mean it's easier for users as well!  I think a good example of the type of code that this fixes is in [this PR/Comment thread](https://github.com/fable-compiler/fable-promise/pull/22#issuecomment-920925118).

**Comment by JohnTheGr8** [comment]
Thanks for taking the time to explain!
